myproject/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = "accounts"

urlpatterns =[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

myproject/diary/urls.py
from django.urls import path
from . import views


app_name = "diary" # アプリ名
urlpatterns = [
    path("", views.index, name="index"), #トップページなので名前はindex
    # ("どんなパスか", パスに対して動く関数, この定義の名前)
    path("page/create/", views.page_create, name="page_create"),
    path("page/list/", views.page_list, name="page_list"),
    path("page/<uuid:id>/", views.page_detail, name="page_detail"),
    # uuidはhtml側で引数を指定
    path("page/<uuid:id>/update/", views.page_update, name="page_update"),
    path("page/<uuid:id>/delete/", views.page_delete, name="page_delete"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include # includeを追加
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("diary/", include("diary.urls")),
    # diary/のURLはdiary.urlsを参照する
    path("accounts/", include("accounts.urls")),
    path("", include("django.contrib.auth.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# static = 開発環境のみで動作
# 画像はクラウド利用が一般的なので仮実装を取る
# static(含まれるURL, 画像の保存フォルダ)

myproject/accounts/models.py
from django.db import models

# Create your models here.

myproject/diary/models.py
from django.db import models
from pathlib import Path
import uuid # 被らないIDを作成

class Page(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    # UUIDをプライマリキー、uuidを自動（デフォルト）設定、編集不可
    title = models.CharField(max_length=100, verbose_name="タイトル")
    body = models.TextField(max_length=2000, verbose_name="本文")
    page_date = models.DateTimeField(verbose_name="日付")
    picture = models.ImageField(
        upload_to="diary/picture/", blank=True, null=True, verbose_name="画像")
    # settings.pyで指定した更にサブフォルダのURL
    # blank=True, null=True 値がなくても可
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    # auto_now_add=True このデータが初めて作成された日時を保存
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")
    # auto_now=True このデータが保存、更新される度に日時を保存
    """
    IntergerField = 数値
    FloatField = 小数点を含む数値
    EmailField = メールアドレス
    BooleanField = 真偽値
    TimeField = 時間
    FileField = ファイル
    ImageField = 画像
    ForeignKey = 外部キー
    """

    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        picture = self.picture
        super().delete(*args, **kwargs)
        if picture:
            Path(picture.path).unlink(missing_ok=True)
    # deleteメソッドをオーバーライドする
    # 元々はページ削除しかできないため、画像も同時に削除する機能を追加
    # super().delete(*args, **kwargs)と関数内に記載して元々のdeleteの機能も保持
    # .unlink() = ファイルを削除 
    # missing_ok=True = ファイルが存在しない場合でもエラーにならない

myproject/diary/forms.py
#リクエストで受け取ったデータのチェック、型変換を自動で行う

from django.forms import ModelForm
from .models import Page

class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ["title", "body", "page_date", "picture"]

myproject/accounts/views.py
from django.shortcuts import render

# Create your views here.

myproject/diary/views.py
#url.pyから呼び出され、ブラウザにレスポンスを返す
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin #ログインを必須にするMixin
from django.views import View # 汎用的なView用の基底クラス
from .forms import PageForm
from .models import Page
from datetime import datetime
from zoneinfo import ZoneInfo

# LoginRequiredMixinは必ず一番最初に追加する必要がある
class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        # 日記アプリのトップページにアクセスした時に動くメソッド
        # request = ユーザーから送られてきたデータを含む

        datetime_now = datetime.now(
                ZoneInfo("Asia/Tokyo")
        ).strftime("%Y年%m月%d日 %H:%M:%S")
        #pythonの処理をhtmlに送ることが可能

        return render(
            request, "diary/index.html",
            {"datetime_now": datetime_now}, # {HTML側の変数:Python側の変数}の辞書
            )
        # render = 画面のレスポンスを返す
        # 返す画面のhtmlを指定

class PageCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = PageForm()
        return render(request, "diary/page_form.html", {"form": form})
        # render(リクエストに対して, 表示するページ, htmlに対応した辞書データ)
    
    def post(self, request):# 保存に対して動くメソッド
        form = PageForm(request.POST, request.FILES)
        if form.is_valid(): # チェックするメッソド。問題なければ保存
            form.save()
            return redirect("diary:index") # diaryアプリ内の名前indexを指定
            # POSTの重複を防ぐため転送が必須
        return render(request, "diary/page_form.html", {"form": form})


class PageListView(LoginRequiredMixin, View):
    def get(self, request):
        page_list = Page.objects.order_by("-page_date") 
        # objects.all() = DBから日記データを全て取得
        # objects.order_by() = ソートする -を付けると降順
        return render(request, "diary/page_list.html", {"page_list": page_list})

class PageDetailView(LoginRequiredMixin, View):
    def get(self, request, id):
        page_detail = get_object_or_404(Page, id=id) 
        # DBからIDが一致するPageのデータを取得 or 404ページ
        return render(request, "diary/page_detail.html", {"page_detail": page_detail})
    

class PageUpdateView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id) 
        form = PageForm(instance=page)
        # 取得したページ内容をformに含めて取得
        return render(request, "diary/page_update.html", {"form": form})
    
    def post(self, request, id):
        page = get_object_or_404(Page, id=id) 
        form = PageForm(request.POST, request.FILES, instance=page)
        if form.is_valid():
            form.save()
            return redirect("diary:page_detail", id=id)
        return render(request, "diary/page_update.html", {"form": form})
    
class PageDeleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        page = get_object_or_404(Page, id=id) 
        return render(request, "diary/page_confirm_delete.html", {"page": page})

    def post(self, request, id):
        page = get_object_or_404(Page, id=id) 
        page.delete()
        return redirect('diary:page_list')
        


index = IndexView.as_view()
    #as_view() = IndexViewクラスを関数に変換(getメソットが動く)
page_create = PageCreateView.as_view()
page_list = PageListView.as_view()
page_detail = PageDetailView.as_view()
page_update = PageUpdateView.as_view()
page_delete = PageDeleteView.as_view()

myproject/templates/base/diary_base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <title>Django日記テストページ</title>
        {% load static %}
        <script src="{% static 'diary/js/base.js' %}"> </script>
    </head>
    <body>
        <h1><a href="{% url 'diary:index' %}">Django日記テストページ</a></h1>
        {% block body %}
        {% endblock %}
    </body>
</html>

myproject/templates/diary/index.html
{% extends "base/diary_base.html" %}
{% block body %}

<p>こちらはpythonの時計</p>
<p>{{ datetime_now }}</p>
<br>
<p>こちらはjavasprictの時計</p>
<div id="clock"></div>
<br>

<a href="{% url 'diary:page_create' %}">日記を書く</a>
<br>
<a href="{% url 'diary:page_list' %}">ページ一覧</a>
<br>
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">ログアウト</button>
</form>

{% endblock %}

myproject/templates/diary/page_confirm_delete.html
{% extends "base/diary_base.html" %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <p>このページを削除して良いですか？</p>
    <button type="submit">削除</button>
</form>
<br>
<h2>{{ page.title }}</h2>
<div>{{ page.page_date }}</div>
<div>{{ page.body | linebreaksbr }}</div>
<!-- linebreaksbr = 改行も反映 -->
{% if page.picture %}
    <img src="{{ page.picture.url }}"/>
{% endif %}

{% endblock %}

myproject/templates/diary/page_detail.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>{{ page_detail.title }}</h2>
<div>{{ page_detail.page_date }}</div>
<div>{{ page_detail.body | linebreaksbr }}</div>
<!-- linebreaksbr = 改行も反映 -->
{% if page_detail.picture %}
    <img src="{{ page_detail.picture.url }}"/>
{% endif %}
<br>
<a href="{% url 'diary:page_update' page_detail.id %}">編集</a>
<a href="{% url 'diary:page_delete' page_detail.id %}">削除</a>

{% endblock %}

myproject/templates/diary/page_form.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>日記を書く</h2>
<form method="POST" enctype="multipart/form-data">
    <!-- リクエストをポストに変換（データ登録はPOST） -->
    {% csrf_token %} <!-- CSRFの検証を自動で行う -->
    {{ form.as_p }} <!-- _.as_p = 定義した入力フィールドを、簡単にHTMLに変換して表示 -->
    <button type="submit">保存</button>
    <!-- submit = 送信 他にresetなどがある -->
</form>

{% endblock %}

myproject/templates/diary/page_list.html
{% extends "base/diary_base.html" %}
{% block body %}

<ul>
    {% for page in page_list %}
    <!-- "for n in list" page_list = DBから取得したすべての日記とview.pyで設定 -->
        <li>{{ page.page_date }}:
             <a href="{% url 'diary:page_detail' page.id %}">{{ page.title }}</a>
        </li>
    {% empty %} <!-- if not page_list -->
        <div>日記のページが１つもありません。</div>
    {% endfor %}
</ul>

{% endblock %}

myproject/templates/diary/page_update.html
{% extends "base/diary_base.html" %}
{% block body %}

<!-- page_detailとほぼ同じ、サーバーサイド側で内容を変更 -->

<h2>日記を編集</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">更新</button>
</form>

{% endblock %}